repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ['--write-changes', '--uri-ignore-words-list=ist']
        exclude: CHANGELOG\.rst|\.(svg|pyc|drawio)$